///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a903fd14-f7ce-40d1-a0ae-a26b479e107b")]
    public partial class WebTestRepository : RepoGenBaseFolder
    {
        static WebTestRepository instance = new WebTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the WebTestRepository element repository.
        /// </summary>
        [RepositoryFolder("a903fd14-f7ce-40d1-a0ae-a26b479e107b")]
        public static WebTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebTestRepository() 
            : base("WebTestRepository", "/", null, 0, false, "a903fd14-f7ce-40d1-a0ae-a26b479e107b", ".\\RepositoryImages\\WebTestRepositorya903fd14.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a903fd14-f7ce-40d1-a0ae-a26b479e107b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WebTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
