///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace report_zoomdata
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the report_zoomdataRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("afc97220-dea7-42e4-9d08-353e6ec6331c")]
    public partial class report_zoomdataRepository : RepoGenBaseFolder
    {
        static report_zoomdataRepository instance = new report_zoomdataRepository();
        report_zoomdataRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        report_zoomdataRepositoryFolders.RanorexStudioQuickStartSeries56EAppFolder _ranorexstudioquickstartseries56e;
        report_zoomdataRepositoryFolders.PricewaterhouseCoopersInternationalLimAppFolder _pricewaterhousecoopersinternationallim;
        report_zoomdataRepositoryFolders.PricewaterhouseCoopersInternationalLim1AppFolder _pricewaterhousecoopersinternationallim1;
        report_zoomdataRepositoryFolders.WorkbenchAppFolder _workbench;

        /// <summary>
        /// Gets the singleton class instance representing the report_zoomdataRepository element repository.
        /// </summary>
        [RepositoryFolder("afc97220-dea7-42e4-9d08-353e6ec6331c")]
        public static report_zoomdataRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public report_zoomdataRepository() 
            : base("report_zoomdataRepository", "/", null, 0, false, "afc97220-dea7-42e4-9d08-353e6ec6331c", ".\\RepositoryImages\\report_zoomdataRepositoryafc97220.rximgres")
        {
            _applicationundertest = new report_zoomdataRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _ranorexstudioquickstartseries56e = new report_zoomdataRepositoryFolders.RanorexStudioQuickStartSeries56EAppFolder(this);
            _pricewaterhousecoopersinternationallim = new report_zoomdataRepositoryFolders.PricewaterhouseCoopersInternationalLimAppFolder(this);
            _pricewaterhousecoopersinternationallim1 = new report_zoomdataRepositoryFolders.PricewaterhouseCoopersInternationalLim1AppFolder(this);
            _workbench = new report_zoomdataRepositoryFolders.WorkbenchAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("afc97220-dea7-42e4-9d08-353e6ec6331c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("d8a8a936-542b-445f-9ac8-f7c45ca76444")]
        public virtual report_zoomdataRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RanorexStudioQuickStartSeries56E folder.
        /// </summary>
        [RepositoryFolder("6ea2ccb6-1bf7-4f22-ad65-781085aa2a82")]
        public virtual report_zoomdataRepositoryFolders.RanorexStudioQuickStartSeries56EAppFolder RanorexStudioQuickStartSeries56E
        {
            get { return _ranorexstudioquickstartseries56e; }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLim folder.
        /// </summary>
        [RepositoryFolder("73983bd9-e60f-43af-ba0c-9a8b2e1232d7")]
        public virtual report_zoomdataRepositoryFolders.PricewaterhouseCoopersInternationalLimAppFolder PricewaterhouseCoopersInternationalLim
        {
            get { return _pricewaterhousecoopersinternationallim; }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLim1 folder.
        /// </summary>
        [RepositoryFolder("3af96d90-5309-46fe-896a-882738b43381")]
        public virtual report_zoomdataRepositoryFolders.PricewaterhouseCoopersInternationalLim1AppFolder PricewaterhouseCoopersInternationalLim1
        {
            get { return _pricewaterhousecoopersinternationallim1; }
        }

        /// <summary>
        /// The Workbench folder.
        /// </summary>
        [RepositoryFolder("a6fee346-4820-4041-85b9-fdcd4f4f9c80")]
        public virtual report_zoomdataRepositoryFolders.WorkbenchAppFolder Workbench
        {
            get { return _workbench; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class report_zoomdataRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8a8a936-542b-445f-9ac8-f7c45ca76444")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='lab.pwc.com']", parentFolder, 30000, null, false, "d8a8a936-542b-445f-9ac8-f7c45ca76444", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8a8a936-542b-445f-9ac8-f7c45ca76444")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8a8a936-542b-445f-9ac8-f7c45ca76444")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RanorexStudioQuickStartSeries56EAppFolder folder.
        /// </summary>
        [RepositoryFolder("6ea2ccb6-1bf7-4f22-ad65-781085aa2a82")]
        public partial class RanorexStudioQuickStartSeries56EAppFolder : RepoGenBaseFolder
        {
            RanorexStudioQuickStartSeries56EInfoClass _ranorexstudioquickstartseries56eInfo;

            /// <summary>
            /// Creates a new RanorexStudioQuickStartSeries56E  folder.
            /// </summary>
            public RanorexStudioQuickStartSeries56EAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexStudioQuickStartSeries56E", "/dom[@domain='www.youtube.com']", parentFolder, 30000, null, false, "6ea2ccb6-1bf7-4f22-ad65-781085aa2a82", "")
            {
                _ranorexstudioquickstartseries56eInfo = new RanorexStudioQuickStartSeries56EInfoClass(this);
            }

            /// <summary>
            /// The RanorexStudioQuickStartSeries56EInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f072e011-2f03-4cff-be24-edad61d8dcc2")]
            public class RanorexStudioQuickStartSeries56EInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RanorexStudioQuickStartSeries56EInfoClass class constructor.
                /// </summary>
                public RanorexStudioQuickStartSeries56EInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RanorexStudioQuickStartSeries56E", "", 30000, null, "f072e011-2f03-4cff-be24-edad61d8dcc2")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("d3093fdf-f4dd-4518-aab5-5956ddca69f6")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("d3093fdf-f4dd-4518-aab5-5956ddca69f6");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d3093fdf-f4dd-4518-aab5-5956ddca69f6")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d3093fdf-f4dd-4518-aab5-5956ddca69f6", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("b1813c70-2dee-4aa1-8bb8-07062441e5c3")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("b1813c70-2dee-4aa1-8bb8-07062441e5c3");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b1813c70-2dee-4aa1-8bb8-07062441e5c3")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b1813c70-2dee-4aa1-8bb8-07062441e5c3", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("19fab237-0602-4514-9365-d26c62b2f003")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("19fab237-0602-4514-9365-d26c62b2f003");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("19fab237-0602-4514-9365-d26c62b2f003")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("19fab237-0602-4514-9365-d26c62b2f003", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("0565f0dc-e16e-4b4f-9d36-55ed0070e751")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("0565f0dc-e16e-4b4f-9d36-55ed0070e751");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0565f0dc-e16e-4b4f-9d36-55ed0070e751")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0565f0dc-e16e-4b4f-9d36-55ed0070e751", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ea2ccb6-1bf7-4f22-ad65-781085aa2a82")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ea2ccb6-1bf7-4f22-ad65-781085aa2a82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioQuickStartSeries56E item.
            /// </summary>
            [RepositoryItem("f072e011-2f03-4cff-be24-edad61d8dcc2")]
            public virtual Ranorex.WebDocument RanorexStudioQuickStartSeries56E
            {
                get
                {
                    return _ranorexstudioquickstartseries56eInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioQuickStartSeries56E item info.
            /// </summary>
            [RepositoryItemInfo("f072e011-2f03-4cff-be24-edad61d8dcc2")]
            public virtual RanorexStudioQuickStartSeries56EInfoClass RanorexStudioQuickStartSeries56EInfo
            {
                get
                {
                    return _ranorexstudioquickstartseries56eInfo;
                }
            }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLimAppFolder folder.
        /// </summary>
        [RepositoryFolder("73983bd9-e60f-43af-ba0c-9a8b2e1232d7")]
        public partial class PricewaterhouseCoopersInternationalLimAppFolder : RepoGenBaseFolder
        {
            Ctl00DollarphCenterDollartxtEMAILInfoClass _ctl00dollarphcenterdollartxtemailInfo;
            Ctl00DollarphCenterDollarbtnSubmitxInfoClass _ctl00dollarphcenterdollarbtnsubmitxInfo;

            /// <summary>
            /// Creates a new PricewaterhouseCoopersInternationalLim  folder.
            /// </summary>
            public PricewaterhouseCoopersInternationalLimAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PricewaterhouseCoopersInternationalLim", "/dom[@domain='broker.pwc.com']", parentFolder, 30000, null, false, "73983bd9-e60f-43af-ba0c-9a8b2e1232d7", "")
            {
                _ctl00dollarphcenterdollartxtemailInfo = new Ctl00DollarphCenterDollartxtEMAILInfoClass(this);
                _ctl00dollarphcenterdollarbtnsubmitxInfo = new Ctl00DollarphCenterDollarbtnSubmitxInfoClass(this);
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtEMAILInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("c63f2cde-f7f2-4b54-b4fa-da302546552d")]
            public class Ctl00DollarphCenterDollartxtEMAILInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Ctl00DollarphCenterDollartxtEMAILInfoClass class constructor.
                /// </summary>
                public Ctl00DollarphCenterDollartxtEMAILInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Ctl00DollarphCenterDollartxtEMAIL", ".//div[#'Main_Wrapper']/div/div[3]/div/div[2]/?/?/table/tbody/tr[2]/?/?/input[@name='ctl00$phCenter$txtEMAIL']", 30000, null, "c63f2cde-f7f2-4b54-b4fa-da302546552d")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("1dc35255-c266-47f1-a3cc-d9ccd7cf26ce")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("1dc35255-c266-47f1-a3cc-d9ccd7cf26ce");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1dc35255-c266-47f1-a3cc-d9ccd7cf26ce")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1dc35255-c266-47f1-a3cc-d9ccd7cf26ce", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("a77a9c21-f9c1-4bcc-9c38-439da8513176")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("a77a9c21-f9c1-4bcc-9c38-439da8513176");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a77a9c21-f9c1-4bcc-9c38-439da8513176")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a77a9c21-f9c1-4bcc-9c38-439da8513176", cropRect);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitxInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("e5f0f9ca-dc19-47cd-9f42-f40e3824c33a")]
            public class Ctl00DollarphCenterDollarbtnSubmitxInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Ctl00DollarphCenterDollarbtnSubmitxInfoClass class constructor.
                /// </summary>
                public Ctl00DollarphCenterDollarbtnSubmitxInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Ctl00DollarphCenterDollarbtnSubmitx", ".//div[#'Main_Wrapper']/div/div[3]/div/div[2]/?/?/table/tbody/tr[5]//input[@name='ctl00$phCenter$btnSubmitx']", 30000, null, "e5f0f9ca-dc19-47cd-9f42-f40e3824c33a")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("0ae925ce-afb9-489e-b820-abeea592024b")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("0ae925ce-afb9-489e-b820-abeea592024b");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0ae925ce-afb9-489e-b820-abeea592024b")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0ae925ce-afb9-489e-b820-abeea592024b", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73983bd9-e60f-43af-ba0c-9a8b2e1232d7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73983bd9-e60f-43af-ba0c-9a8b2e1232d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtEMAIL item.
            /// </summary>
            [RepositoryItem("c63f2cde-f7f2-4b54-b4fa-da302546552d")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollartxtEMAIL
            {
                get
                {
                    return _ctl00dollarphcenterdollartxtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtEMAIL item info.
            /// </summary>
            [RepositoryItemInfo("c63f2cde-f7f2-4b54-b4fa-da302546552d")]
            public virtual Ctl00DollarphCenterDollartxtEMAILInfoClass Ctl00DollarphCenterDollartxtEMAILInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollartxtemailInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitx item.
            /// </summary>
            [RepositoryItem("e5f0f9ca-dc19-47cd-9f42-f40e3824c33a")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollarbtnSubmitx
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitx item info.
            /// </summary>
            [RepositoryItemInfo("e5f0f9ca-dc19-47cd-9f42-f40e3824c33a")]
            public virtual Ctl00DollarphCenterDollarbtnSubmitxInfoClass Ctl00DollarphCenterDollarbtnSubmitxInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitxInfo;
                }
            }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLim1AppFolder folder.
        /// </summary>
        [RepositoryFolder("3af96d90-5309-46fe-896a-882738b43381")]
        public partial class PricewaterhouseCoopersInternationalLim1AppFolder : RepoGenBaseFolder
        {
            PricewaterhouseCoopersInternationalLimInfoClass _pricewaterhousecoopersinternationallimInfo;
            Ctl00DollarphCenterDollarbtnSubmitInfoClass _ctl00dollarphcenterdollarbtnsubmitInfo;
            RepoItemInfo _ctl00dollarphcenterdollartxtpasswordInfo;

            /// <summary>
            /// Creates a new PricewaterhouseCoopersInternationalLim1  folder.
            /// </summary>
            public PricewaterhouseCoopersInternationalLim1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("PricewaterhouseCoopersInternationalLim1", "/dom[@domain='gx.fedsvc.pwc.com']", parentFolder, 30000, null, false, "3af96d90-5309-46fe-896a-882738b43381", "")
            {
                _pricewaterhousecoopersinternationallimInfo = new PricewaterhouseCoopersInternationalLimInfoClass(this);
                _ctl00dollarphcenterdollarbtnsubmitInfo = new Ctl00DollarphCenterDollarbtnSubmitInfoClass(this);
                _ctl00dollarphcenterdollartxtpasswordInfo = new RepoItemInfo(this, "Ctl00DollarphCenterDollartxtPassword", ".//form[#'aspnetForm']/div[3]/div[3]/div/div/div[2]//input[@name='ctl00$phCenter$txtPassword']", 30000, null, "21f644bf-71f4-4b7b-9099-bd5fd5239d0a");
            }

            /// <summary>
            /// The PricewaterhouseCoopersInternationalLimInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("36bb4c61-1276-49cb-857f-f529853a8aa5")]
            public class PricewaterhouseCoopersInternationalLimInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PricewaterhouseCoopersInternationalLimInfoClass class constructor.
                /// </summary>
                public PricewaterhouseCoopersInternationalLimInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PricewaterhouseCoopersInternationalLim", "", 30000, null, "36bb4c61-1276-49cb-857f-f529853a8aa5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("cd979b4f-1d30-4945-8b4f-521a1ef9cf91")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("cd979b4f-1d30-4945-8b4f-521a1ef9cf91");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("cd979b4f-1d30-4945-8b4f-521a1ef9cf91")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("cd979b4f-1d30-4945-8b4f-521a1ef9cf91", cropRect);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("94257767-b407-4a4b-9835-d29c78d90585")]
            public class Ctl00DollarphCenterDollarbtnSubmitInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Ctl00DollarphCenterDollarbtnSubmitInfoClass class constructor.
                /// </summary>
                public Ctl00DollarphCenterDollarbtnSubmitInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Ctl00DollarphCenterDollarbtnSubmit", ".//form[#'aspnetForm']/div[3]/div[3]/div/div/div[2]//input[@name='ctl00$phCenter$btnSubmit']", 30000, null, "94257767-b407-4a4b-9835-d29c78d90585")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("0a505df7-0f71-45b9-a50a-81de76b95877")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("0a505df7-0f71-45b9-a50a-81de76b95877");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0a505df7-0f71-45b9-a50a-81de76b95877")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0a505df7-0f71-45b9-a50a-81de76b95877", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3af96d90-5309-46fe-896a-882738b43381")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3af96d90-5309-46fe-896a-882738b43381")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PricewaterhouseCoopersInternationalLim item.
            /// </summary>
            [RepositoryItem("36bb4c61-1276-49cb-857f-f529853a8aa5")]
            public virtual Ranorex.WebDocument PricewaterhouseCoopersInternationalLim
            {
                get
                {
                    return _pricewaterhousecoopersinternationallimInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The PricewaterhouseCoopersInternationalLim item info.
            /// </summary>
            [RepositoryItemInfo("36bb4c61-1276-49cb-857f-f529853a8aa5")]
            public virtual PricewaterhouseCoopersInternationalLimInfoClass PricewaterhouseCoopersInternationalLimInfo
            {
                get
                {
                    return _pricewaterhousecoopersinternationallimInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmit item.
            /// </summary>
            [RepositoryItem("94257767-b407-4a4b-9835-d29c78d90585")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollarbtnSubmit
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("94257767-b407-4a4b-9835-d29c78d90585")]
            public virtual Ctl00DollarphCenterDollarbtnSubmitInfoClass Ctl00DollarphCenterDollarbtnSubmitInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtPassword item.
            /// </summary>
            [RepositoryItem("21f644bf-71f4-4b7b-9099-bd5fd5239d0a")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollartxtPassword
            {
                get
                {
                    return _ctl00dollarphcenterdollartxtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("21f644bf-71f4-4b7b-9099-bd5fd5239d0a")]
            public virtual RepoItemInfo Ctl00DollarphCenterDollartxtPasswordInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollartxtpasswordInfo;
                }
            }
        }

        /// <summary>
        /// The WorkbenchAppFolder folder.
        /// </summary>
        [RepositoryFolder("a6fee346-4820-4041-85b9-fdcd4f4f9c80")]
        public partial class WorkbenchAppFolder : RepoGenBaseFolder
        {
            report_zoomdataRepositoryFolders.AllowDeferredRenderingVisualVisualPFolder _allowdeferredrenderingvisualvisualp;
            VIEWSHAREDREPORTSInfoClass _viewsharedreportsInfo;
            SharedReportsInputSearchInfoClass _sharedreportsinputsearchInfo;
            LeaguesAndTeamsInfoClass _leaguesandteamsInfo;
            WidgetContentInfoClass _widgetcontentInfo;
            SomeCanvasTagInfoClass _somecanvastagInfo;
            ScrollWrapperInfoClass _scrollwrapperInfo;

            /// <summary>
            /// Creates a new Workbench  folder.
            /// </summary>
            public WorkbenchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Workbench", "/dom[@domain='workbench-us.pwc.com']", parentFolder, 30000, null, false, "a6fee346-4820-4041-85b9-fdcd4f4f9c80", "")
            {
                _allowdeferredrenderingvisualvisualp = new report_zoomdataRepositoryFolders.AllowDeferredRenderingVisualVisualPFolder(this);
                _viewsharedreportsInfo = new VIEWSHAREDREPORTSInfoClass(this);
                _sharedreportsinputsearchInfo = new SharedReportsInputSearchInfoClass(this);
                _leaguesandteamsInfo = new LeaguesAndTeamsInfoClass(this);
                _widgetcontentInfo = new WidgetContentInfoClass(this);
                _somecanvastagInfo = new SomeCanvasTagInfoClass(this);
                _scrollwrapperInfo = new ScrollWrapperInfoClass(this);
            }

            /// <summary>
            /// The VIEWSHAREDREPORTSInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("cb0442ed-875f-4e0c-825a-8ad0ce595949")]
            public class VIEWSHAREDREPORTSInfoClass : RepoItemInfo
            {
                /// <summary>
                /// VIEWSHAREDREPORTSInfoClass class constructor.
                /// </summary>
                public VIEWSHAREDREPORTSInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "VIEWSHAREDREPORTS", ".//nav[#'navbar']/div/div[2]/?/?/div[@innertext='VIEW SHARED REPORTS']", 30000, null, "cb0442ed-875f-4e0c-825a-8ad0ce595949")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("848f0435-5924-463e-9150-8b64f0b05ff2")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("848f0435-5924-463e-9150-8b64f0b05ff2");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("848f0435-5924-463e-9150-8b64f0b05ff2")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("848f0435-5924-463e-9150-8b64f0b05ff2", cropRect);
                }
            }

            /// <summary>
            /// The SharedReportsInputSearchInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("cf63fb85-0c62-459a-a12d-303ba79c5df3")]
            public class SharedReportsInputSearchInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SharedReportsInputSearchInfoClass class constructor.
                /// </summary>
                public SharedReportsInputSearchInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SharedReportsInputSearch", ".//input[#'sharedReports-input-search']", 30000, null, "cf63fb85-0c62-459a-a12d-303ba79c5df3")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("de2de7c3-28fd-41ba-aa25-49f581856273")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("de2de7c3-28fd-41ba-aa25-49f581856273");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("de2de7c3-28fd-41ba-aa25-49f581856273")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("de2de7c3-28fd-41ba-aa25-49f581856273", cropRect);
                }
            }

            /// <summary>
            /// The LeaguesAndTeamsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("48737207-727f-41b3-9a28-2b7f8613ac11")]
            public class LeaguesAndTeamsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// LeaguesAndTeamsInfoClass class constructor.
                /// </summary>
                public LeaguesAndTeamsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "LeaguesAndTeams", ".//div[#'tile-div-openReport']/div[@innertext='Leagues and Teams']", 30000, null, "48737207-727f-41b3-9a28-2b7f8613ac11")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("b483a831-1113-494c-99d2-576ba26ff078")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("b483a831-1113-494c-99d2-576ba26ff078");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b483a831-1113-494c-99d2-576ba26ff078")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b483a831-1113-494c-99d2-576ba26ff078", cropRect);
                }
            }

            /// <summary>
            /// The WidgetContentInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("199c61e1-ba9b-46fb-bf88-3a65647bd6e2")]
            public class WidgetContentInfoClass : RepoItemInfo
            {
                /// <summary>
                /// WidgetContentInfoClass class constructor.
                /// </summary>
                public WidgetContentInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "WidgetContent", ".//iframe[#'iframe1']/body/div[6]/section/div/div[2]/div[2]/div[1]/div/div/div[2]/div/div/div[3]/div[2]/div[3]", 30000, null, "199c61e1-ba9b-46fb-bf88-3a65647bd6e2")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("c4d1fd72-7def-4946-9d97-aee6f709b16d")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("c4d1fd72-7def-4946-9d97-aee6f709b16d");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c4d1fd72-7def-4946-9d97-aee6f709b16d")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c4d1fd72-7def-4946-9d97-aee6f709b16d", cropRect);
                }
            }

            /// <summary>
            /// The SomeCanvasTagInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("27a72731-9d82-488d-a05c-03bdd19ee678")]
            public class SomeCanvasTagInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SomeCanvasTagInfoClass class constructor.
                /// </summary>
                public SomeCanvasTagInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SomeCanvasTag", ".//iframe[#'iframe1']/body/div[6]/section/div/div[2]/div[2]/div[1]/div/div/div[2]/div/div/div[3]/div[2]/div[3]//canvas", 30000, null, "27a72731-9d82-488d-a05c-03bdd19ee678")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("aaca34f2-3559-487b-8968-4741dfd7dc91")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("aaca34f2-3559-487b-8968-4741dfd7dc91");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("aaca34f2-3559-487b-8968-4741dfd7dc91")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("aaca34f2-3559-487b-8968-4741dfd7dc91", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("fee68e97-3e01-4e26-b6fd-07cf193559b8")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("fee68e97-3e01-4e26-b6fd-07cf193559b8");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("fee68e97-3e01-4e26-b6fd-07cf193559b8")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("fee68e97-3e01-4e26-b6fd-07cf193559b8", cropRect);
                }
            }

            /// <summary>
            /// The ScrollWrapperInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("0dfa6b24-9ab0-4dea-93b9-92f076e174a0")]
            public class ScrollWrapperInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ScrollWrapperInfoClass class constructor.
                /// </summary>
                public ScrollWrapperInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ScrollWrapper", ".//iframe[#'iframe1']//div[#'reportContainer']/iframe[@src='https://app.powerbi.com/reportEmbed?reportId=3e99a5aa-b0ac-4902-8a1e-676e4231d690&groupId=db202fa3-2186-4ccc-973d-a25f541c6491&w=2&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVdFU1QtVVMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQiLCJlbWJlZEZlYXR1cmVzIjp7Im1vZGVybkVtYmVkIjpmYWxzZX19']//tag[#'pvExplorationHost']/div/div[2]//tag[@tagname='explore-canvas-modern']/div/div[2]/div/div[2]/div[2]/tag/tag[4]/tag[@tagname='transform']/div/div[3]/tag/div/div", 30000, null, "0dfa6b24-9ab0-4dea-93b9-92f076e174a0")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2b614c60-0765-47b9-b435-76a0d0c21d5e")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2b614c60-0765-47b9-b435-76a0d0c21d5e");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2b614c60-0765-47b9-b435-76a0d0c21d5e")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2b614c60-0765-47b9-b435-76a0d0c21d5e", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a6fee346-4820-4041-85b9-fdcd4f4f9c80")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6fee346-4820-4041-85b9-fdcd4f4f9c80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VIEWSHAREDREPORTS item.
            /// </summary>
            [RepositoryItem("cb0442ed-875f-4e0c-825a-8ad0ce595949")]
            public virtual Ranorex.DivTag VIEWSHAREDREPORTS
            {
                get
                {
                    return _viewsharedreportsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The VIEWSHAREDREPORTS item info.
            /// </summary>
            [RepositoryItemInfo("cb0442ed-875f-4e0c-825a-8ad0ce595949")]
            public virtual VIEWSHAREDREPORTSInfoClass VIEWSHAREDREPORTSInfo
            {
                get
                {
                    return _viewsharedreportsInfo;
                }
            }

            /// <summary>
            /// The SharedReportsInputSearch item.
            /// </summary>
            [RepositoryItem("cf63fb85-0c62-459a-a12d-303ba79c5df3")]
            public virtual Ranorex.InputTag SharedReportsInputSearch
            {
                get
                {
                    return _sharedreportsinputsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SharedReportsInputSearch item info.
            /// </summary>
            [RepositoryItemInfo("cf63fb85-0c62-459a-a12d-303ba79c5df3")]
            public virtual SharedReportsInputSearchInfoClass SharedReportsInputSearchInfo
            {
                get
                {
                    return _sharedreportsinputsearchInfo;
                }
            }

            /// <summary>
            /// The LeaguesAndTeams item.
            /// </summary>
            [RepositoryItem("48737207-727f-41b3-9a28-2b7f8613ac11")]
            public virtual Ranorex.DivTag LeaguesAndTeams
            {
                get
                {
                    return _leaguesandteamsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LeaguesAndTeams item info.
            /// </summary>
            [RepositoryItemInfo("48737207-727f-41b3-9a28-2b7f8613ac11")]
            public virtual LeaguesAndTeamsInfoClass LeaguesAndTeamsInfo
            {
                get
                {
                    return _leaguesandteamsInfo;
                }
            }

            /// <summary>
            /// The WidgetContent item.
            /// </summary>
            [RepositoryItem("199c61e1-ba9b-46fb-bf88-3a65647bd6e2")]
            public virtual Ranorex.DivTag WidgetContent
            {
                get
                {
                    return _widgetcontentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The WidgetContent item info.
            /// </summary>
            [RepositoryItemInfo("199c61e1-ba9b-46fb-bf88-3a65647bd6e2")]
            public virtual WidgetContentInfoClass WidgetContentInfo
            {
                get
                {
                    return _widgetcontentInfo;
                }
            }

            /// <summary>
            /// The SomeCanvasTag item.
            /// </summary>
            [RepositoryItem("27a72731-9d82-488d-a05c-03bdd19ee678")]
            public virtual Ranorex.CanvasTag SomeCanvasTag
            {
                get
                {
                    return _somecanvastagInfo.CreateAdapter<Ranorex.CanvasTag>(true);
                }
            }

            /// <summary>
            /// The SomeCanvasTag item info.
            /// </summary>
            [RepositoryItemInfo("27a72731-9d82-488d-a05c-03bdd19ee678")]
            public virtual SomeCanvasTagInfoClass SomeCanvasTagInfo
            {
                get
                {
                    return _somecanvastagInfo;
                }
            }

            /// <summary>
            /// The ScrollWrapper item.
            /// </summary>
            [RepositoryItem("0dfa6b24-9ab0-4dea-93b9-92f076e174a0")]
            public virtual Ranorex.DivTag ScrollWrapper
            {
                get
                {
                    return _scrollwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ScrollWrapper item info.
            /// </summary>
            [RepositoryItemInfo("0dfa6b24-9ab0-4dea-93b9-92f076e174a0")]
            public virtual ScrollWrapperInfoClass ScrollWrapperInfo
            {
                get
                {
                    return _scrollwrapperInfo;
                }
            }

            /// <summary>
            /// The AllowDeferredRenderingVisualVisualP folder.
            /// </summary>
            [RepositoryFolder("072f0969-e32f-48f6-aa1b-6f9fdc0469d0")]
            public virtual report_zoomdataRepositoryFolders.AllowDeferredRenderingVisualVisualPFolder AllowDeferredRenderingVisualVisualP
            {
                get { return _allowdeferredrenderingvisualvisualp; }
            }
        }

        /// <summary>
        /// The AllowDeferredRenderingVisualVisualPFolder folder.
        /// </summary>
        [RepositoryFolder("072f0969-e32f-48f6-aa1b-6f9fdc0469d0")]
        public partial class AllowDeferredRenderingVisualVisualPFolder : RepoGenBaseFolder
        {
            RectInfoClass _rectInfo;
            Path1InfoClass _path1Info;
            PathInfoClass _pathInfo;

            /// <summary>
            /// Creates a new AllowDeferredRenderingVisualVisualP  folder.
            /// </summary>
            public AllowDeferredRenderingVisualVisualPFolder(RepoGenBaseFolder parentFolder) :
                    base("AllowDeferredRenderingVisualVisualP", ".//iframe[#'iframe1']//div[#'reportContainer']/iframe[@src='https://app.powerbi.com/reportEmbed?reportId=3e99a5aa-b0ac-4902-8a1e-676e4231d690&groupId=db202fa3-2186-4ccc-973d-a25f541c6491&w=2&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVdFU1QtVVMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQiLCJlbWJlZEZlYXR1cmVzIjp7Im1vZGVybkVtYmVkIjpmYWxzZX19']//tag[#'pvExplorationHost']/div/div[2]//tag[@tagname='explore-canvas-modern']/div/div[2]/div/div[2]/div[2]/tag/tag[2]/tag[@tagname='transform']/div/div[3]/tag[@tagname='visual-modern']/div", parentFolder, 30000, null, false, "072f0969-e32f-48f6-aa1b-6f9fdc0469d0", "")
            {
                _rectInfo = new RectInfoClass(this);
                _path1Info = new Path1InfoClass(this);
                _pathInfo = new PathInfoClass(this);
            }

            /// <summary>
            /// The RectInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("db3e36b2-1237-40de-bbf9-cd3aa36c7f7c")]
            public class RectInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RectInfoClass class constructor.
                /// </summary>
                public RectInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Rect", "?/?/tag[@tagname='rect']", 30000, null, "db3e36b2-1237-40de-bbf9-cd3aa36c7f7c")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("525a0ec4-21fa-40d4-bf4c-a13daded9774")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("525a0ec4-21fa-40d4-bf4c-a13daded9774");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("525a0ec4-21fa-40d4-bf4c-a13daded9774")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("525a0ec4-21fa-40d4-bf4c-a13daded9774", cropRect);
                }
            }

            /// <summary>
            /// The Path1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("c7423040-8cea-4924-9ab7-602ae4549925")]
            public class Path1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// Path1InfoClass class constructor.
                /// </summary>
                public Path1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Path1", "tag[@tagname='svg']/tag[2]/tag[@tagname='g']/tag[4]", 30000, null, "c7423040-8cea-4924-9ab7-602ae4549925")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("34592680-6eb6-41b8-becc-8b4167a01583")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("34592680-6eb6-41b8-becc-8b4167a01583");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("34592680-6eb6-41b8-becc-8b4167a01583")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("34592680-6eb6-41b8-becc-8b4167a01583", cropRect);
                }
            }

            /// <summary>
            /// The PathInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("6446ac6a-ad86-4a02-815a-179334732107")]
            public class PathInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PathInfoClass class constructor.
                /// </summary>
                public PathInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Path", "tag[@tagname='svg']/tag[2]/tag[@tagname='g']/tag[5]", 30000, null, "6446ac6a-ad86-4a02-815a-179334732107")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("b36db6f5-6e50-4e1a-80a6-31a4de1d2bdb")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("b36db6f5-6e50-4e1a-80a6-31a4de1d2bdb");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b36db6f5-6e50-4e1a-80a6-31a4de1d2bdb")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b36db6f5-6e50-4e1a-80a6-31a4de1d2bdb", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("072f0969-e32f-48f6-aa1b-6f9fdc0469d0")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("072f0969-e32f-48f6-aa1b-6f9fdc0469d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Rect item.
            /// </summary>
            [RepositoryItem("db3e36b2-1237-40de-bbf9-cd3aa36c7f7c")]
            public virtual Ranorex.WebElement Rect
            {
                get
                {
                    return _rectInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Rect item info.
            /// </summary>
            [RepositoryItemInfo("db3e36b2-1237-40de-bbf9-cd3aa36c7f7c")]
            public virtual RectInfoClass RectInfo
            {
                get
                {
                    return _rectInfo;
                }
            }

            /// <summary>
            /// The Path1 item.
            /// </summary>
            [RepositoryItem("c7423040-8cea-4924-9ab7-602ae4549925")]
            public virtual Ranorex.WebElement Path1
            {
                get
                {
                    return _path1Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path1 item info.
            /// </summary>
            [RepositoryItemInfo("c7423040-8cea-4924-9ab7-602ae4549925")]
            public virtual Path1InfoClass Path1Info
            {
                get
                {
                    return _path1Info;
                }
            }

            /// <summary>
            /// The Path item.
            /// </summary>
            [RepositoryItem("6446ac6a-ad86-4a02-815a-179334732107")]
            public virtual Ranorex.WebElement Path
            {
                get
                {
                    return _pathInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path item info.
            /// </summary>
            [RepositoryItemInfo("6446ac6a-ad86-4a02-815a-179334732107")]
            public virtual PathInfoClass PathInfo
            {
                get
                {
                    return _pathInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
