///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace zoomreport2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the zoomreport2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a503252b-f7b1-4fd8-af08-ae997bbb2ae4")]
    public partial class zoomreport2Repository : RepoGenBaseFolder
    {
        static zoomreport2Repository instance = new zoomreport2Repository();
        zoomreport2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        zoomreport2RepositoryFolders.PricewaterhouseCoopersInternationalLimAppFolder _pricewaterhousecoopersinternationallim;
        zoomreport2RepositoryFolders.PricewaterhouseCoopersInternationalLim1AppFolder _pricewaterhousecoopersinternationallim1;
        zoomreport2RepositoryFolders.WorkbenchAppFolder _workbench;

        /// <summary>
        /// Gets the singleton class instance representing the zoomreport2Repository element repository.
        /// </summary>
        [RepositoryFolder("a503252b-f7b1-4fd8-af08-ae997bbb2ae4")]
        public static zoomreport2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public zoomreport2Repository() 
            : base("zoomreport2Repository", "/", null, 0, false, "a503252b-f7b1-4fd8-af08-ae997bbb2ae4", ".\\RepositoryImages\\zoomreport2Repositorya503252b.rximgres")
        {
            _applicationundertest = new zoomreport2RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _pricewaterhousecoopersinternationallim = new zoomreport2RepositoryFolders.PricewaterhouseCoopersInternationalLimAppFolder(this);
            _pricewaterhousecoopersinternationallim1 = new zoomreport2RepositoryFolders.PricewaterhouseCoopersInternationalLim1AppFolder(this);
            _workbench = new zoomreport2RepositoryFolders.WorkbenchAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a503252b-f7b1-4fd8-af08-ae997bbb2ae4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("462c5b13-89c6-4339-84b2-1252aba3e1b9")]
        public virtual zoomreport2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLim folder.
        /// </summary>
        [RepositoryFolder("5e6cf7ca-e1e6-4769-a850-14a0e698958a")]
        public virtual zoomreport2RepositoryFolders.PricewaterhouseCoopersInternationalLimAppFolder PricewaterhouseCoopersInternationalLim
        {
            get { return _pricewaterhousecoopersinternationallim; }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLim1 folder.
        /// </summary>
        [RepositoryFolder("be74e560-fd5e-4589-ae35-1f7ee246d138")]
        public virtual zoomreport2RepositoryFolders.PricewaterhouseCoopersInternationalLim1AppFolder PricewaterhouseCoopersInternationalLim1
        {
            get { return _pricewaterhousecoopersinternationallim1; }
        }

        /// <summary>
        /// The Workbench folder.
        /// </summary>
        [RepositoryFolder("53b35789-b25d-4c9d-a3bc-822a5dbe2506")]
        public virtual zoomreport2RepositoryFolders.WorkbenchAppFolder Workbench
        {
            get { return _workbench; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class zoomreport2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("462c5b13-89c6-4339-84b2-1252aba3e1b9")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='lab.pwc.com']", parentFolder, 30000, null, false, "462c5b13-89c6-4339-84b2-1252aba3e1b9", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("462c5b13-89c6-4339-84b2-1252aba3e1b9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("462c5b13-89c6-4339-84b2-1252aba3e1b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLimAppFolder folder.
        /// </summary>
        [RepositoryFolder("5e6cf7ca-e1e6-4769-a850-14a0e698958a")]
        public partial class PricewaterhouseCoopersInternationalLimAppFolder : RepoGenBaseFolder
        {
            Ctl00DollarphCenterDollartxtEMAILInfoClass _ctl00dollarphcenterdollartxtemailInfo;
            Ctl00DollarphCenterDollarbtnSubmitxInfoClass _ctl00dollarphcenterdollarbtnsubmitxInfo;

            /// <summary>
            /// Creates a new PricewaterhouseCoopersInternationalLim  folder.
            /// </summary>
            public PricewaterhouseCoopersInternationalLimAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PricewaterhouseCoopersInternationalLim", "/dom[@domain='broker.pwc.com']", parentFolder, 30000, null, false, "5e6cf7ca-e1e6-4769-a850-14a0e698958a", "")
            {
                _ctl00dollarphcenterdollartxtemailInfo = new Ctl00DollarphCenterDollartxtEMAILInfoClass(this);
                _ctl00dollarphcenterdollarbtnsubmitxInfo = new Ctl00DollarphCenterDollarbtnSubmitxInfoClass(this);
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtEMAILInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("ce34c677-5063-48ca-ad3a-f3c2bca9a134")]
            public class Ctl00DollarphCenterDollartxtEMAILInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Ctl00DollarphCenterDollartxtEMAILInfoClass class constructor.
                /// </summary>
                public Ctl00DollarphCenterDollartxtEMAILInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Ctl00DollarphCenterDollartxtEMAIL", ".//div[#'Main_Wrapper']/div/div[3]/div/div[2]/?/?/table/tbody/tr[2]/?/?/input[@name='ctl00$phCenter$txtEMAIL']", 30000, null, "ce34c677-5063-48ca-ad3a-f3c2bca9a134")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("54d64634-be7d-412d-9f9b-744d2d3005be")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("54d64634-be7d-412d-9f9b-744d2d3005be");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("54d64634-be7d-412d-9f9b-744d2d3005be")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("54d64634-be7d-412d-9f9b-744d2d3005be", cropRect);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitxInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5ddffdcf-4952-48fa-86dd-4166a5337e35")]
            public class Ctl00DollarphCenterDollarbtnSubmitxInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Ctl00DollarphCenterDollarbtnSubmitxInfoClass class constructor.
                /// </summary>
                public Ctl00DollarphCenterDollarbtnSubmitxInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Ctl00DollarphCenterDollarbtnSubmitx", ".//div[#'Main_Wrapper']/div/div[3]/div/div[2]/?/?/table/tbody/tr[5]//input[@name='ctl00$phCenter$btnSubmitx']", 30000, null, "5ddffdcf-4952-48fa-86dd-4166a5337e35")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("4704bbbd-feeb-457e-a13c-74118b9e0fb6")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("4704bbbd-feeb-457e-a13c-74118b9e0fb6");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4704bbbd-feeb-457e-a13c-74118b9e0fb6")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4704bbbd-feeb-457e-a13c-74118b9e0fb6", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e6cf7ca-e1e6-4769-a850-14a0e698958a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e6cf7ca-e1e6-4769-a850-14a0e698958a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtEMAIL item.
            /// </summary>
            [RepositoryItem("ce34c677-5063-48ca-ad3a-f3c2bca9a134")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollartxtEMAIL
            {
                get
                {
                    return _ctl00dollarphcenterdollartxtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollartxtEMAIL item info.
            /// </summary>
            [RepositoryItemInfo("ce34c677-5063-48ca-ad3a-f3c2bca9a134")]
            public virtual Ctl00DollarphCenterDollartxtEMAILInfoClass Ctl00DollarphCenterDollartxtEMAILInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollartxtemailInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitx item.
            /// </summary>
            [RepositoryItem("5ddffdcf-4952-48fa-86dd-4166a5337e35")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollarbtnSubmitx
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitx item info.
            /// </summary>
            [RepositoryItemInfo("5ddffdcf-4952-48fa-86dd-4166a5337e35")]
            public virtual Ctl00DollarphCenterDollarbtnSubmitxInfoClass Ctl00DollarphCenterDollarbtnSubmitxInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitxInfo;
                }
            }
        }

        /// <summary>
        /// The PricewaterhouseCoopersInternationalLim1AppFolder folder.
        /// </summary>
        [RepositoryFolder("be74e560-fd5e-4589-ae35-1f7ee246d138")]
        public partial class PricewaterhouseCoopersInternationalLim1AppFolder : RepoGenBaseFolder
        {
            FormFormGroupInfoClass _formformgroupInfo;
            PricewaterhouseCoopersInternationalLimInfoClass _pricewaterhousecoopersinternationallimInfo;
            Ctl00DollarphCenterDollarbtnSubmitInfoClass _ctl00dollarphcenterdollarbtnsubmitInfo;

            /// <summary>
            /// Creates a new PricewaterhouseCoopersInternationalLim1  folder.
            /// </summary>
            public PricewaterhouseCoopersInternationalLim1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("PricewaterhouseCoopersInternationalLim1", "/dom[@domain='gx.fedsvc.pwc.com']", parentFolder, 30000, null, false, "be74e560-fd5e-4589-ae35-1f7ee246d138", "")
            {
                _formformgroupInfo = new FormFormGroupInfoClass(this);
                _pricewaterhousecoopersinternationallimInfo = new PricewaterhouseCoopersInternationalLimInfoClass(this);
                _ctl00dollarphcenterdollarbtnsubmitInfo = new Ctl00DollarphCenterDollarbtnSubmitInfoClass(this);
            }

            /// <summary>
            /// The FormFormGroupInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3c4aaf97-d6ef-4ae3-b8f2-a105994a14aa")]
            public class FormFormGroupInfoClass : RepoItemInfo
            {
                /// <summary>
                /// FormFormGroupInfoClass class constructor.
                /// </summary>
                public FormFormGroupInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "FormFormGroup", ".//form[#'aspnetForm']/div[3]/div[3]/div/div/div[2]/div[1]", 30000, null, "3c4aaf97-d6ef-4ae3-b8f2-a105994a14aa")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("5aa96f15-2acc-4288-9da2-1d44dacb83d5")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("5aa96f15-2acc-4288-9da2-1d44dacb83d5");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5aa96f15-2acc-4288-9da2-1d44dacb83d5")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5aa96f15-2acc-4288-9da2-1d44dacb83d5", cropRect);
                }
            }

            /// <summary>
            /// The PricewaterhouseCoopersInternationalLimInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("48f47a06-9f22-4ec7-851d-6645e61f2b99")]
            public class PricewaterhouseCoopersInternationalLimInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PricewaterhouseCoopersInternationalLimInfoClass class constructor.
                /// </summary>
                public PricewaterhouseCoopersInternationalLimInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PricewaterhouseCoopersInternationalLim", "", 30000, null, "48f47a06-9f22-4ec7-851d-6645e61f2b99")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("b208a23d-c397-4287-9088-f66cdadfebde")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("b208a23d-c397-4287-9088-f66cdadfebde");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b208a23d-c397-4287-9088-f66cdadfebde")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b208a23d-c397-4287-9088-f66cdadfebde", cropRect);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmitInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("fbfbc3df-e2e6-427e-970b-dfe73e157fa8")]
            public class Ctl00DollarphCenterDollarbtnSubmitInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Ctl00DollarphCenterDollarbtnSubmitInfoClass class constructor.
                /// </summary>
                public Ctl00DollarphCenterDollarbtnSubmitInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Ctl00DollarphCenterDollarbtnSubmit", ".//form[#'aspnetForm']/div[3]/div[3]/div/div/div[2]//input[@name='ctl00$phCenter$btnSubmit']", 30000, null, "fbfbc3df-e2e6-427e-970b-dfe73e157fa8")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("255f04cb-f9d9-4551-afec-e915048c67fe")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("255f04cb-f9d9-4551-afec-e915048c67fe");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("255f04cb-f9d9-4551-afec-e915048c67fe")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("255f04cb-f9d9-4551-afec-e915048c67fe", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be74e560-fd5e-4589-ae35-1f7ee246d138")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be74e560-fd5e-4589-ae35-1f7ee246d138")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FormFormGroup item.
            /// </summary>
            [RepositoryItem("3c4aaf97-d6ef-4ae3-b8f2-a105994a14aa")]
            public virtual Ranorex.DivTag FormFormGroup
            {
                get
                {
                    return _formformgroupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FormFormGroup item info.
            /// </summary>
            [RepositoryItemInfo("3c4aaf97-d6ef-4ae3-b8f2-a105994a14aa")]
            public virtual FormFormGroupInfoClass FormFormGroupInfo
            {
                get
                {
                    return _formformgroupInfo;
                }
            }

            /// <summary>
            /// The PricewaterhouseCoopersInternationalLim item.
            /// </summary>
            [RepositoryItem("48f47a06-9f22-4ec7-851d-6645e61f2b99")]
            public virtual Ranorex.WebDocument PricewaterhouseCoopersInternationalLim
            {
                get
                {
                    return _pricewaterhousecoopersinternationallimInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The PricewaterhouseCoopersInternationalLim item info.
            /// </summary>
            [RepositoryItemInfo("48f47a06-9f22-4ec7-851d-6645e61f2b99")]
            public virtual PricewaterhouseCoopersInternationalLimInfoClass PricewaterhouseCoopersInternationalLimInfo
            {
                get
                {
                    return _pricewaterhousecoopersinternationallimInfo;
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmit item.
            /// </summary>
            [RepositoryItem("fbfbc3df-e2e6-427e-970b-dfe73e157fa8")]
            public virtual Ranorex.InputTag Ctl00DollarphCenterDollarbtnSubmit
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ctl00DollarphCenterDollarbtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("fbfbc3df-e2e6-427e-970b-dfe73e157fa8")]
            public virtual Ctl00DollarphCenterDollarbtnSubmitInfoClass Ctl00DollarphCenterDollarbtnSubmitInfo
            {
                get
                {
                    return _ctl00dollarphcenterdollarbtnsubmitInfo;
                }
            }
        }

        /// <summary>
        /// The WorkbenchAppFolder folder.
        /// </summary>
        [RepositoryFolder("53b35789-b25d-4c9d-a3bc-822a5dbe2506")]
        public partial class WorkbenchAppFolder : RepoGenBaseFolder
        {
            WorkbenchInfoClass _workbenchInfo;
            SharedReportsInputSearchInfoClass _sharedreportsinputsearchInfo;
            LeaguesAndTeamsInfoClass _leaguesandteamsInfo;
            SomeCanvasTagInfoClass _somecanvastagInfo;

            /// <summary>
            /// Creates a new Workbench  folder.
            /// </summary>
            public WorkbenchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Workbench", "/dom[@domain='workbench-us.pwc.com']", parentFolder, 30000, null, false, "53b35789-b25d-4c9d-a3bc-822a5dbe2506", "")
            {
                _workbenchInfo = new WorkbenchInfoClass(this);
                _sharedreportsinputsearchInfo = new SharedReportsInputSearchInfoClass(this);
                _leaguesandteamsInfo = new LeaguesAndTeamsInfoClass(this);
                _somecanvastagInfo = new SomeCanvasTagInfoClass(this);
            }

            /// <summary>
            /// The WorkbenchInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("42d67fc6-ad72-46b5-b814-49c2a77abfcc")]
            public class WorkbenchInfoClass : RepoItemInfo
            {
                /// <summary>
                /// WorkbenchInfoClass class constructor.
                /// </summary>
                public WorkbenchInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Workbench", "", 30000, null, "42d67fc6-ad72-46b5-b814-49c2a77abfcc")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("b153c3eb-1692-4f08-8d63-c254c4d59449")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("b153c3eb-1692-4f08-8d63-c254c4d59449");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b153c3eb-1692-4f08-8d63-c254c4d59449")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b153c3eb-1692-4f08-8d63-c254c4d59449", cropRect);
                }
            }

            /// <summary>
            /// The SharedReportsInputSearchInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("c0d7d674-ff11-4652-a829-946748189227")]
            public class SharedReportsInputSearchInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SharedReportsInputSearchInfoClass class constructor.
                /// </summary>
                public SharedReportsInputSearchInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SharedReportsInputSearch", ".//input[#'sharedReports-input-search']", 30000, null, "c0d7d674-ff11-4652-a829-946748189227")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("5cefd94c-964c-48ea-9656-06e839a82d83")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("5cefd94c-964c-48ea-9656-06e839a82d83");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5cefd94c-964c-48ea-9656-06e839a82d83")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5cefd94c-964c-48ea-9656-06e839a82d83", cropRect);
                }
            }

            /// <summary>
            /// The LeaguesAndTeamsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("4cf7abb7-7fac-4053-9a03-818e4567dc2d")]
            public class LeaguesAndTeamsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// LeaguesAndTeamsInfoClass class constructor.
                /// </summary>
                public LeaguesAndTeamsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "LeaguesAndTeams", ".//div[#'tile-div-openReport']/div[@innertext='Leagues and Teams']", 30000, null, "4cf7abb7-7fac-4053-9a03-818e4567dc2d")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("891e7033-8a51-4acd-a063-253f9b60def4")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("891e7033-8a51-4acd-a063-253f9b60def4");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("891e7033-8a51-4acd-a063-253f9b60def4")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("891e7033-8a51-4acd-a063-253f9b60def4", cropRect);
                }
            }

            /// <summary>
            /// The SomeCanvasTagInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("d1a0d179-eca7-46d6-927d-abf4fb4ea3be")]
            public class SomeCanvasTagInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SomeCanvasTagInfoClass class constructor.
                /// </summary>
                public SomeCanvasTagInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SomeCanvasTag", ".//iframe[#'iframe1']/body/div[6]/section/div/div[2]/div[2]/div[1]/div/div/div[2]/div/div/div[3]/div[2]/div[3]//canvas", 30000, null, "d1a0d179-eca7-46d6-927d-abf4fb4ea3be")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e9209c8c-4c8e-4cb7-b659-d5fe9cd16a87")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e9209c8c-4c8e-4cb7-b659-d5fe9cd16a87");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e9209c8c-4c8e-4cb7-b659-d5fe9cd16a87")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e9209c8c-4c8e-4cb7-b659-d5fe9cd16a87", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("c061ac82-b373-4aa3-8b6b-1a1550a305d5")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("c061ac82-b373-4aa3-8b6b-1a1550a305d5");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c061ac82-b373-4aa3-8b6b-1a1550a305d5")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c061ac82-b373-4aa3-8b6b-1a1550a305d5", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("53b35789-b25d-4c9d-a3bc-822a5dbe2506")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("53b35789-b25d-4c9d-a3bc-822a5dbe2506")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Workbench item.
            /// </summary>
            [RepositoryItem("42d67fc6-ad72-46b5-b814-49c2a77abfcc")]
            public virtual Ranorex.WebDocument Workbench
            {
                get
                {
                    return _workbenchInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Workbench item info.
            /// </summary>
            [RepositoryItemInfo("42d67fc6-ad72-46b5-b814-49c2a77abfcc")]
            public virtual WorkbenchInfoClass WorkbenchInfo
            {
                get
                {
                    return _workbenchInfo;
                }
            }

            /// <summary>
            /// The SharedReportsInputSearch item.
            /// </summary>
            [RepositoryItem("c0d7d674-ff11-4652-a829-946748189227")]
            public virtual Ranorex.InputTag SharedReportsInputSearch
            {
                get
                {
                    return _sharedreportsinputsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SharedReportsInputSearch item info.
            /// </summary>
            [RepositoryItemInfo("c0d7d674-ff11-4652-a829-946748189227")]
            public virtual SharedReportsInputSearchInfoClass SharedReportsInputSearchInfo
            {
                get
                {
                    return _sharedreportsinputsearchInfo;
                }
            }

            /// <summary>
            /// The LeaguesAndTeams item.
            /// </summary>
            [RepositoryItem("4cf7abb7-7fac-4053-9a03-818e4567dc2d")]
            public virtual Ranorex.DivTag LeaguesAndTeams
            {
                get
                {
                    return _leaguesandteamsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LeaguesAndTeams item info.
            /// </summary>
            [RepositoryItemInfo("4cf7abb7-7fac-4053-9a03-818e4567dc2d")]
            public virtual LeaguesAndTeamsInfoClass LeaguesAndTeamsInfo
            {
                get
                {
                    return _leaguesandteamsInfo;
                }
            }

            /// <summary>
            /// The SomeCanvasTag item.
            /// </summary>
            [RepositoryItem("d1a0d179-eca7-46d6-927d-abf4fb4ea3be")]
            public virtual Ranorex.CanvasTag SomeCanvasTag
            {
                get
                {
                    return _somecanvastagInfo.CreateAdapter<Ranorex.CanvasTag>(true);
                }
            }

            /// <summary>
            /// The SomeCanvasTag item info.
            /// </summary>
            [RepositoryItemInfo("d1a0d179-eca7-46d6-927d-abf4fb4ea3be")]
            public virtual SomeCanvasTagInfoClass SomeCanvasTagInfo
            {
                get
                {
                    return _somecanvastagInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
